In [32]:
#Importing the libraries

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [3]:
#importing the dataset

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/earthchem_download_95122.txt', delimiter = "\t")
dataset

SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
0      080385-4   NaN  GEOROC  ...     NaN     NaN       NaN
1      230483-3   NaN  GEOROC  ...     NaN     NaN       NaN
2      PU-02-34   NaN  GEOROC  ...     NaN     NaN       NaN
3      PU-02-25   NaN  GEOROC  ...     NaN     NaN       NaN
4      PU-02-20   NaN  GEOROC  ...     NaN     NaN       NaN
...         ...   ...     ...  ...     ...     ...       ...
3058  DBF-03-05   NaN  GEOROC  ...     NaN     NaN       NaN
3059    DBF04-6   NaN  GEOROC  ...     NaN     NaN       NaN
3060    DBF04-5   NaN  GEOROC  ...     NaN     NaN       NaN
3061    CHO 099   NaN  GEOROC  ...     NaN     0.0       NaN
3062    LAU-2/2   NaN  GEOROC  ...     NaN     NaN       NaN

[3063 rows x 151 columns]

**EXPLORATORY DATA ANALYSIS**

In [8]:
#top 5 rows

dataset.head()

SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
0  080385-4   NaN  GEOROC  ...     NaN     NaN       NaN
1  230483-3   NaN  GEOROC  ...     NaN     NaN       NaN
2  PU-02-34   NaN  GEOROC  ...     NaN     NaN       NaN
3  PU-02-25   NaN  GEOROC  ...     NaN     NaN       NaN
4  PU-02-20   NaN  GEOROC  ...     NaN     NaN       NaN

[5 rows x 151 columns]

In [9]:
#last 5 rows
dataset.tail()

SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
3058  DBF-03-05   NaN  GEOROC  ...     NaN     NaN       NaN
3059    DBF04-6   NaN  GEOROC  ...     NaN     NaN       NaN
3060    DBF04-5   NaN  GEOROC  ...     NaN     NaN       NaN
3061    CHO 099   NaN  GEOROC  ...     NaN     0.0       NaN
3062    LAU-2/2   NaN  GEOROC  ...     NaN     NaN       NaN

[5 rows x 151 columns]

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3063 entries, 0 to 3062
Columns: 151 entries, SAMPLE ID to INDIUM.1
dtypes: float64(133), object(18)
memory usage: 3.5+ MB


In [11]:
dataset.info

<bound method DataFrame.info of       SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
0      080385-4   NaN  GEOROC  ...     NaN     NaN       NaN
1      230483-3   NaN  GEOROC  ...     NaN     NaN       NaN
2      PU-02-34   NaN  GEOROC  ...     NaN     NaN       NaN
3      PU-02-25   NaN  GEOROC  ...     NaN     NaN       NaN
4      PU-02-20   NaN  GEOROC  ...     NaN     NaN       NaN
...         ...   ...     ...  ...     ...     ...       ...
3058  DBF-03-05   NaN  GEOROC  ...     NaN     NaN       NaN
3059    DBF04-6   NaN  GEOROC  ...     NaN     NaN       NaN
3060    DBF04-5   NaN  GEOROC  ...     NaN     NaN       NaN
3061    CHO 099   NaN  GEOROC  ...     NaN     0.0       NaN
3062    LAU-2/2   NaN  GEOROC  ...     NaN     NaN       NaN

[3063 rows x 151 columns]>

In [12]:
dataset.keys()

Index(['SAMPLE ID', 'IGSN', 'SOURCE', 'REFERENCE', 'CRUISE ID', 'LATITUDE',
       'LONGITUDE', 'LOC PREC', 'MIN AGE', 'AGE',
       ...
       'ZR', 'TI.1', 'AS.2', 'AS.3', 'GER.1', 'H2O_M.1', 'H2O_P.1', 'H2O_M.2',
       'H2O_P.2', 'INDIUM.1'],
      dtype='object', length=151)

In [13]:
dataset.describe()

IGSN     LATITUDE    LONGITUDE  ...    H2O_M.2     H2O_P.2  INDIUM.1
count   0.0  3063.000000  3063.000000  ...  81.000000  163.000000       3.0
mean    NaN   -29.436414   -69.961676  ...   0.562716    0.966994       0.0
std     NaN     9.817008     2.227382  ...   0.535546    0.875199       0.0
min     NaN   -54.800000   -78.518000  ...   0.000000    0.000000       0.0
25%     NaN   -38.769400   -71.699050  ...   0.200000    0.210000       0.0
50%     NaN   -26.420000   -70.250000  ...   0.330000    0.790000       0.0
75%     NaN   -21.246800   -68.000000  ...   0.750000    1.510000       0.0
max     NaN    -6.975000   -64.440000  ...   2.530000    4.860000       0.0

[8 rows x 133 columns]

In [14]:
dataset.dtypes

SAMPLE ID     object
IGSN         float64
SOURCE        object
REFERENCE     object
CRUISE ID     object
              ...   
H2O_M.1      float64
H2O_P.1      float64
H2O_M.2      float64
H2O_P.2      float64
INDIUM.1     float64
Length: 151, dtype: object

**Checking the values of SIO2**

In [16]:
#To see if a sample is obsidian, we need to check their SIO2 values
dataset.iloc[:, 16:17]

SIO2
0     69.144
1     63.541
2     70.931
3     70.047
4     69.367
...      ...
3058  64.904
3059     NaN
3060     NaN
3061  66.728
3062  75.179

[3063 rows x 1 columns]

**TAKING CARE OF MISSING VALUES**

In [20]:
#drop independent features with less then 50% values

limitPer = len(dataset) * .50
dataset = dataset.dropna(thresh=limitPer, axis=1)

In [21]:
dataset.columns

Index(['SAMPLE ID', 'SOURCE', 'REFERENCE', 'LATITUDE', 'LONGITUDE', 'LOC PREC',
       'MATERIAL', 'TYPE', 'COMPOSITION', 'ROCK NAME', 'SIO2', 'TIO2', 'AL2O3',
       'FEOT', 'MNO', 'MGO', 'CAO', 'NA2O', 'K2O', 'P2O5', 'BA', 'RB', 'SR',
       'TH', 'ZR'],
      dtype='object')

In [22]:
dataset

SAMPLE ID  SOURCE  ...     TH     ZR
0      080385-4  GEOROC  ...   8.60  282.0
1      230483-3  GEOROC  ...   4.30  195.0
2      PU-02-34  GEOROC  ...   8.30  307.0
3      PU-02-25  GEOROC  ...   9.18  342.0
4      PU-02-20  GEOROC  ...   8.82  308.0
...         ...     ...  ...    ...    ...
3058  DBF-03-05  GEOROC  ...    NaN    NaN
3059    DBF04-6  GEOROC  ...    NaN    NaN
3060    DBF04-5  GEOROC  ...    NaN    NaN
3061    CHO 099  GEOROC  ...   5.00  101.0
3062    LAU-2/2  GEOROC  ...  20.17  150.0

[3063 rows x 25 columns]

In [27]:
#dropping values with no SIO2 values

dataset = dataset.dropna(subset=['SIO2'])

In [28]:
dataset

SAMPLE ID  SOURCE  ...     TH     ZR
0      080385-4  GEOROC  ...   8.60  282.0
1      230483-3  GEOROC  ...   4.30  195.0
2      PU-02-34  GEOROC  ...   8.30  307.0
3      PU-02-25  GEOROC  ...   9.18  342.0
4      PU-02-20  GEOROC  ...   8.82  308.0
...         ...     ...  ...    ...    ...
3056    AJO 017  GEOROC  ...   4.00   73.0
3057     AJO017  GEOROC  ...  16.30  121.0
3058  DBF-03-05  GEOROC  ...    NaN    NaN
3061    CHO 099  GEOROC  ...   5.00  101.0
3062    LAU-2/2  GEOROC  ...  20.17  150.0

[2140 rows x 25 columns]

**ENCODING CATEGORICAL DATA**

In [30]:
datasetpro = dataset.copy()

In [31]:
datasetpro

SAMPLE ID  SOURCE  ...     TH     ZR
0      080385-4  GEOROC  ...   8.60  282.0
1      230483-3  GEOROC  ...   4.30  195.0
2      PU-02-34  GEOROC  ...   8.30  307.0
3      PU-02-25  GEOROC  ...   9.18  342.0
4      PU-02-20  GEOROC  ...   8.82  308.0
...         ...     ...  ...    ...    ...
3056    AJO 017  GEOROC  ...   4.00   73.0
3057     AJO017  GEOROC  ...  16.30  121.0
3058  DBF-03-05  GEOROC  ...    NaN    NaN
3061    CHO 099  GEOROC  ...   5.00  101.0
3062    LAU-2/2  GEOROC  ...  20.17  150.0

[2140 rows x 25 columns]

In [37]:
X = dataset.iloc[:, 10:].values

In [39]:
print(X)

[[6.9144e+01 5.6500e-01 1.4590e+01 ... 1.9000e+02 8.6000e+00 2.8200e+02]
 [6.3541e+01 7.9600e-01 1.6427e+01 ... 2.9400e+02 4.3000e+00 1.9500e+02]
 [7.0931e+01 3.4000e-01 1.3794e+01 ... 1.3800e+02 8.3000e+00 3.0700e+02]
 ...
 [6.4904e+01 8.3400e-01 1.6277e+01 ...        nan        nan        nan]
 [6.6728e+01 5.5500e-01 1.7025e+01 ... 5.0800e+02 5.0000e+00 1.0100e+02]
 [7.5179e+01 1.2900e-01 1.3810e+01 ... 1.1250e+03 2.0170e+01 1.5000e+02]]


In [40]:
y = dataset.iloc[:, 9:10].values

In [42]:
print(y)

[['dacite']
 ['dacite']
 ['dacite']
 ...
 ['dacite']
 ['dacite']
 ['rhyolite']]


In [45]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y2 = le.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
print(y2)

[0 0 0 ... 0 0 2]


In [47]:
y2

array([0, 0, 0, ..., 0, 0, 2])

In [51]:
#Splitting the data into training and testing set

In [54]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y2, test_size = 0.2, random_state = 42)

In [55]:
print(X1_train)

[[6.4418e+01 5.0900e-01 1.7428e+01 ...        nan        nan        nan]
 [7.1638e+01 4.3000e-01 1.4899e+01 ... 6.6100e+02 9.2000e+00        nan]
 [6.7959e+01 5.3100e-01 1.5382e+01 ... 3.2900e+02 2.5000e+01 2.5700e+02]
 ...
 [6.7668e+01 5.3600e-01 1.5467e+01 ... 3.3100e+02 1.3330e+01 1.7000e+02]
 [7.6003e+01 1.5400e-01 1.3301e+01 ... 1.2000e+02 5.7300e+00 8.1000e+01]
 [6.5354e+01 6.6400e-01 1.5728e+01 ... 4.2200e+02 1.5000e+01 1.4000e+02]]


In [56]:
print(X1_test)

[[7.6793e+01 1.8000e-01 1.2844e+01 ... 4.0000e+01 1.8410e+01        nan]
 [6.4544e+01 8.2300e-01 1.5653e+01 ... 5.6000e+02 1.1800e+01 1.6600e+02]
 [6.5753e+01 6.0000e-01 1.6758e+01 ...        nan        nan        nan]
 ...
 [6.5769e+01 6.4000e-01 1.6216e+01 ... 3.4000e+02 1.0000e+01 2.3100e+02]
 [6.7128e+01 8.7100e-01 1.7411e+01 ... 1.0000e+03        nan 2.0000e+02]
 [7.0675e+01 3.6700e-01 1.5220e+01 ...        nan        nan        nan]]


In [57]:
print(y1_test)

[2 0 0 1 0 0 3 2 0 2 2 2 0 0 0 0 1 0 2 2 0 2 0 2 2 2 0 2 2 0 0 2 1 1 0 2 2
 0 0 2 2 0 2 0 0 2 0 2 2 2 0 2 0 0 0 0 2 2 2 0 2 0 0 0 0 2 2 1 0 0 2 0 1 0
 0 0 0 2 2 2 2 1 0 0 0 0 2 2 0 0 0 0 0 0 1 2 0 0 0 0 2 0 0 2 0 0 2 0 0 0 0
 0 0 0 2 0 0 0 2 1 0 0 2 0 2 0 2 0 0 0 0 2 2 2 0 0 0 1 2 0 0 0 0 0 0 2 2 0
 0 0 0 0 0 0 1 0 4 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 0 1
 0 0 0 0 2 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 2 0 2 1 1 2 0 0 0 2 2 1
 3 2 1 0 0 0 0 0 0 2 0 0 2 0 2 0 0 2 1 2 0 0 1 0 0 0 2 0 0 0 0 0 2 0 2 0 2
 2 2 1 2 2 0 0 0 0 2 0 2 0 2 0 1 0 0 0 0 0 2 0 0 0 0 0 0 2 0 2 0 2 0 0 2 0
 2 2 2 0 0 0 2 0 2 0 0 0 0 0 2 0 2 0 0 2 2 0 0 2 0 0 0 0 0 2 0 2 0 0 0 0 2
 1 2 0 2 2 0 0 2 0 0 1 1 2 1 2 0 0 0 0 2 0 0 2 1 0 1 0 0 0 0 0 0 1 0 0 0 2
 0 2 1 1 2 0 0 2 2 0 2 0 0 0 0 0 0 2 2 0 0 1 0 2 0 2 2 0 0 0 2 0 0 0 2 0 0
 0 2 2 0 2 0 0 2 0 0 0 0 0 2 1 0 0 2 0 3 0]


In [58]:
print(y1_train)

[0 0 0 ... 0 2 0]
