In [1]:
#Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression

In [3]:
#importing the dataset

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/earthchem_download_95122.txt', delimiter = "\t")
dataset

SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
0      080385-4   NaN  GEOROC  ...     NaN     NaN       NaN
1      230483-3   NaN  GEOROC  ...     NaN     NaN       NaN
2      PU-02-34   NaN  GEOROC  ...     NaN     NaN       NaN
3      PU-02-25   NaN  GEOROC  ...     NaN     NaN       NaN
4      PU-02-20   NaN  GEOROC  ...     NaN     NaN       NaN
...         ...   ...     ...  ...     ...     ...       ...
3058  DBF-03-05   NaN  GEOROC  ...     NaN     NaN       NaN
3059    DBF04-6   NaN  GEOROC  ...     NaN     NaN       NaN
3060    DBF04-5   NaN  GEOROC  ...     NaN     NaN       NaN
3061    CHO 099   NaN  GEOROC  ...     NaN     0.0       NaN
3062    LAU-2/2   NaN  GEOROC  ...     NaN     NaN       NaN

[3063 rows x 151 columns]

**EXPLORATORY DATA ANALYSIS**

In [5]:
#top 5 rows

dataset.head()

SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
0  080385-4   NaN  GEOROC  ...     NaN     NaN       NaN
1  230483-3   NaN  GEOROC  ...     NaN     NaN       NaN
2  PU-02-34   NaN  GEOROC  ...     NaN     NaN       NaN
3  PU-02-25   NaN  GEOROC  ...     NaN     NaN       NaN
4  PU-02-20   NaN  GEOROC  ...     NaN     NaN       NaN

[5 rows x 151 columns]

In [6]:
#last 5 rows
dataset.tail()

SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
3058  DBF-03-05   NaN  GEOROC  ...     NaN     NaN       NaN
3059    DBF04-6   NaN  GEOROC  ...     NaN     NaN       NaN
3060    DBF04-5   NaN  GEOROC  ...     NaN     NaN       NaN
3061    CHO 099   NaN  GEOROC  ...     NaN     0.0       NaN
3062    LAU-2/2   NaN  GEOROC  ...     NaN     NaN       NaN

[5 rows x 151 columns]

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3063 entries, 0 to 3062
Columns: 151 entries, SAMPLE ID to INDIUM.1
dtypes: float64(133), object(18)
memory usage: 3.5+ MB


In [8]:
dataset.info

<bound method DataFrame.info of       SAMPLE ID  IGSN  SOURCE  ... H2O_M.2 H2O_P.2  INDIUM.1
0      080385-4   NaN  GEOROC  ...     NaN     NaN       NaN
1      230483-3   NaN  GEOROC  ...     NaN     NaN       NaN
2      PU-02-34   NaN  GEOROC  ...     NaN     NaN       NaN
3      PU-02-25   NaN  GEOROC  ...     NaN     NaN       NaN
4      PU-02-20   NaN  GEOROC  ...     NaN     NaN       NaN
...         ...   ...     ...  ...     ...     ...       ...
3058  DBF-03-05   NaN  GEOROC  ...     NaN     NaN       NaN
3059    DBF04-6   NaN  GEOROC  ...     NaN     NaN       NaN
3060    DBF04-5   NaN  GEOROC  ...     NaN     NaN       NaN
3061    CHO 099   NaN  GEOROC  ...     NaN     0.0       NaN
3062    LAU-2/2   NaN  GEOROC  ...     NaN     NaN       NaN

[3063 rows x 151 columns]>

In [9]:
dataset.keys()

Index(['SAMPLE ID', 'IGSN', 'SOURCE', 'REFERENCE', 'CRUISE ID', 'LATITUDE',
       'LONGITUDE', 'LOC PREC', 'MIN AGE', 'AGE',
       ...
       'ZR', 'TI.1', 'AS.2', 'AS.3', 'GER.1', 'H2O_M.1', 'H2O_P.1', 'H2O_M.2',
       'H2O_P.2', 'INDIUM.1'],
      dtype='object', length=151)

In [10]:
dataset.describe()

IGSN     LATITUDE    LONGITUDE  ...    H2O_M.2     H2O_P.2  INDIUM.1
count   0.0  3063.000000  3063.000000  ...  81.000000  163.000000       3.0
mean    NaN   -29.436414   -69.961676  ...   0.562716    0.966994       0.0
std     NaN     9.817008     2.227382  ...   0.535546    0.875199       0.0
min     NaN   -54.800000   -78.518000  ...   0.000000    0.000000       0.0
25%     NaN   -38.769400   -71.699050  ...   0.200000    0.210000       0.0
50%     NaN   -26.420000   -70.250000  ...   0.330000    0.790000       0.0
75%     NaN   -21.246800   -68.000000  ...   0.750000    1.510000       0.0
max     NaN    -6.975000   -64.440000  ...   2.530000    4.860000       0.0

[8 rows x 133 columns]

In [11]:
dataset.dtypes

SAMPLE ID     object
IGSN         float64
SOURCE        object
REFERENCE     object
CRUISE ID     object
              ...   
H2O_M.1      float64
H2O_P.1      float64
H2O_M.2      float64
H2O_P.2      float64
INDIUM.1     float64
Length: 151, dtype: object

**Checking the values of SIO2**

In [12]:
#To see if a sample is obsidian, we need to check their SIO2 values
dataset.iloc[:, 16:17]

SIO2
0     69.144
1     63.541
2     70.931
3     70.047
4     69.367
...      ...
3058  64.904
3059     NaN
3060     NaN
3061  66.728
3062  75.179

[3063 rows x 1 columns]

**TAKING CARE OF MISSING VALUES**

In [13]:
#drop independent features with less then 50% values

limitPer = len(dataset) * .50
dataset = dataset.dropna(thresh=limitPer, axis=1)

In [14]:
dataset.columns

Index(['SAMPLE ID', 'SOURCE', 'REFERENCE', 'LATITUDE', 'LONGITUDE', 'LOC PREC',
       'MATERIAL', 'TYPE', 'COMPOSITION', 'ROCK NAME', 'SIO2', 'TIO2', 'AL2O3',
       'FEOT', 'MNO', 'MGO', 'CAO', 'NA2O', 'K2O', 'P2O5', 'BA', 'RB', 'SR',
       'TH', 'ZR'],
      dtype='object')

In [15]:
dataset

SAMPLE ID  SOURCE  ...     TH     ZR
0      080385-4  GEOROC  ...   8.60  282.0
1      230483-3  GEOROC  ...   4.30  195.0
2      PU-02-34  GEOROC  ...   8.30  307.0
3      PU-02-25  GEOROC  ...   9.18  342.0
4      PU-02-20  GEOROC  ...   8.82  308.0
...         ...     ...  ...    ...    ...
3058  DBF-03-05  GEOROC  ...    NaN    NaN
3059    DBF04-6  GEOROC  ...    NaN    NaN
3060    DBF04-5  GEOROC  ...    NaN    NaN
3061    CHO 099  GEOROC  ...   5.00  101.0
3062    LAU-2/2  GEOROC  ...  20.17  150.0

[3063 rows x 25 columns]

In [16]:
#dropping values with no SIO2 values

dataset = dataset.dropna(subset=['SIO2'])

In [17]:
dataset

SAMPLE ID  SOURCE  ...     TH     ZR
0      080385-4  GEOROC  ...   8.60  282.0
1      230483-3  GEOROC  ...   4.30  195.0
2      PU-02-34  GEOROC  ...   8.30  307.0
3      PU-02-25  GEOROC  ...   9.18  342.0
4      PU-02-20  GEOROC  ...   8.82  308.0
...         ...     ...  ...    ...    ...
3056    AJO 017  GEOROC  ...   4.00   73.0
3057     AJO017  GEOROC  ...  16.30  121.0
3058  DBF-03-05  GEOROC  ...    NaN    NaN
3061    CHO 099  GEOROC  ...   5.00  101.0
3062    LAU-2/2  GEOROC  ...  20.17  150.0

[2140 rows x 25 columns]

**ENCODING CATEGORICAL DATA**

In [42]:
datasetpro = dataset.copy()

In [43]:
datasetpro

SAMPLE ID  SOURCE  ...     TH     ZR
0      080385-4  GEOROC  ...   8.60  282.0
1      230483-3  GEOROC  ...   4.30  195.0
2      PU-02-34  GEOROC  ...   8.30  307.0
3      PU-02-25  GEOROC  ...   9.18  342.0
4      PU-02-20  GEOROC  ...   8.82  308.0
...         ...     ...  ...    ...    ...
3056    AJO 017  GEOROC  ...   4.00   73.0
3057     AJO017  GEOROC  ...  16.30  121.0
3058  DBF-03-05  GEOROC  ...    NaN    NaN
3061    CHO 099  GEOROC  ...   5.00  101.0
3062    LAU-2/2  GEOROC  ...  20.17  150.0

[2140 rows x 25 columns]

In [44]:

datasetpro = datasetpro.dropna()
#datasetpro = datasetpro.reset_index(drop=True)
datasetpro

SAMPLE ID  SOURCE  ...     TH     ZR
0     080385-4  GEOROC  ...   8.60  282.0
1     230483-3  GEOROC  ...   4.30  195.0
2     PU-02-34  GEOROC  ...   8.30  307.0
3     PU-02-25  GEOROC  ...   9.18  342.0
4     PU-02-20  GEOROC  ...   8.82  308.0
...        ...     ...  ...    ...    ...
3055    RIG187  GEOROC  ...  18.40  108.0
3056   AJO 017  GEOROC  ...   4.00   73.0
3057    AJO017  GEOROC  ...  16.30  121.0
3061   CHO 099  GEOROC  ...   5.00  101.0
3062   LAU-2/2  GEOROC  ...  20.17  150.0

[1161 rows x 25 columns]

In [45]:
X = datasetpro.iloc[:, 10:].values

In [46]:
print(X)

[[6.9144e+01 5.6500e-01 1.4590e+01 ... 1.9000e+02 8.6000e+00 2.8200e+02]
 [6.3541e+01 7.9600e-01 1.6427e+01 ... 2.9400e+02 4.3000e+00 1.9500e+02]
 [7.0931e+01 3.4000e-01 1.3794e+01 ... 1.3800e+02 8.3000e+00 3.0700e+02]
 ...
 [7.5237e+01 2.5800e-01 1.3388e+01 ... 1.4700e+02 1.6300e+01 1.2100e+02]
 [6.6728e+01 5.5500e-01 1.7025e+01 ... 5.0800e+02 5.0000e+00 1.0100e+02]
 [7.5179e+01 1.2900e-01 1.3810e+01 ... 1.1250e+03 2.0170e+01 1.5000e+02]]


In [47]:
y = datasetpro.iloc[:, 9:10].values

In [48]:
print(y)

[['dacite']
 ['dacite']
 ['dacite']
 ...
 ['rhyolite']
 ['dacite']
 ['rhyolite']]


In [49]:
le = LabelEncoder()
y2 = le.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [50]:
print(y2)

[0 0 0 ... 2 0 2]


In [51]:
y2

array([0, 0, 0, ..., 2, 0, 2])

**Splitting the dataset into the Training set and Test set**

In [52]:
#Splitting the data into training and testing set

In [53]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y2, test_size = 0.2, random_state = 42)

In [54]:
print(X1_train)

[[ 63.422   0.825  16.913 ... 508.      9.    213.   ]
 [ 66.261   0.596  16.308 ... 465.     19.6   204.   ]
 [ 63.911   0.885  15.983 ... 578.     15.1   230.   ]
 ...
 [ 64.588   0.67   16.647 ... 550.     19.    205.   ]
 [ 66.034   0.672  15.763 ... 438.     11.8   114.   ]
 [ 69.851   0.6    15.089 ... 236.2    21.3   196.5  ]]


In [55]:
print(X1_test)

[[ 67.668    0.536   15.467  ... 331.      13.33   170.    ]
 [ 71.737    0.667   13.211  ... 127.3      9.7    224.4   ]
 [ 69.393    0.543   15.561  ... 302.06    22.7073 174.543 ]
 ...
 [ 66.607    0.509   17.261  ... 339.      15.     211.    ]
 [ 66.375    0.631   15.909  ... 494.      11.7    124.    ]
 [ 69.705    0.571   15.249  ... 310.199   23.9092 166.    ]]


In [56]:
print(y1_test)

[0 0 0 0 1 2 0 0 0 0 0 0 1 2 0 0 0 0 2 0 0 0 0 0 0 0 2 0 2 0 0 0 0 2 0 0 2
 0 2 2 0 2 0 0 0 0 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 1 0 2 0 0 0 0 2 0 0 2 0
 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 2 2 2 0 0 0 0 0 0 0 0 2 0 0 0 0 1 0 0 0 0 0
 0 2 2 2 0 1 0 1 0 0 0 1 0 0 0 0 2 2 0 0 1 1 0 0 0 0 0 0 2 0 0 0 0 0 0 2 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 2 1 0 0 2 2 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 2 0 0
 0 1 0 0 2 0 0 2 0 2 0 0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 2 2 0 0 0 0 2 0 2
 2 0 0 0 0 2 0 0 0 0 0]


In [57]:
print(y1_train)

[0 0 0 0 0 2 0 0 2 0 1 0 2 0 0 0 0 0 0 0 2 0 0 0 2 2 0 2 2 2 0 0 0 2 0 2 0
 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 2 0 0 2 0 0 0 2 2 1 0 2 2 0 0 0 3 1 2 0 0 0
 0 1 0 1 0 0 1 2 0 0 2 0 0 0 2 1 0 0 2 2 0 2 0 0 0 0 2 0 2 2 0 2 0 0 2 2 2
 2 2 2 0 0 0 0 2 0 0 0 0 2 1 0 0 2 2 2 0 0 0 2 1 0 2 0 2 0 2 0 0 0 0 2 0 2
 2 0 0 2 0 0 0 0 0 0 0 2 2 0 0 0 0 0 2 0 0 0 0 0 1 2 0 0 0 1 0 2 2 0 2 0 0
 0 0 0 2 0 2 2 1 1 0 2 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 0 2 0 0 0 0
 0 0 0 0 2 2 0 1 0 0 0 0 0 0 0 0 0 2 0 0 1 0 2 2 0 0 2 0 0 1 0 2 0 0 0 0 2
 0 2 0 1 0 0 2 0 0 2 0 0 0 0 0 0 1 2 0 0 0 2 2 0 0 0 1 0 0 0 1 0 2 0 0 0 2
 2 0 2 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 0 0 0 1 0 2 0 0 2 0 0 0 0 2 2 0
 0 0 2 2 0 0 2 0 3 0 0 0 0 0 2 2 0 0 1 0 1 0 0 0 2 2 0 0 0 1 2 0 1 2 0 2 0
 0 0 2 0 0 1 1 0 2 2 1 0 0 0 0 2 0 0 0 0 2 0 2 0 0 1 0 0 0 0 0 2 0 0 0 2 0
 2 0 0 0 2 0 0 0 0 2 1 0 0 0 0 2 2 0 0 0 0 0 0 1 0 2 0 0 0 0 1 1 0 2 0 2 0
 0 1 0 0 0 2 1 2 2 0 0 1 0 0 0 0 0 0 0 1 0 2 0 0 0 0 1 0 1 0 2 2 0 2 0 2 0
 0 0 1 2 0 2 0 0 0 0 0 2 

**FEATURE SCALING**

In [58]:
#perform feature scaling using StandardScalar

In [59]:
sc = StandardScaler()
X1_train = sc.fit_transform(X1_train)
X1_test = sc.transform(X1_test)

In [60]:
print(X1_train)

[[-1.45640866  1.29871372  1.26968465 ...  0.67968831 -0.59172444
   0.21845325]
 [-0.76142495  0.3265232   0.81202372 ...  0.50270272  0.61854314
   0.1503478 ]
 [-1.33670206  1.55343613  0.56617281 ...  0.96780438  0.1047503
   0.34709687]
 ...
 [-1.1709733   0.64068084  1.06846513 ...  0.85255795  0.55003743
   0.15791508]
 [-0.81699427  0.64917158  0.39975065 ...  0.39157223 -0.27203112
  -0.53070666]
 [ 0.11740264  0.34350469 -0.11010632 ... -0.43902525  0.81264266
   0.09359327]]


In [61]:
print(X1_test)

[[-0.41699308  0.07180079  0.1758372  ... -0.04883376 -0.09734155
  -0.10693944]
 [ 0.57909313  0.62794472 -1.53074636 ... -0.88725154 -0.51180111
   0.30472015]
 [ 0.0052848   0.10151841  0.24694485 ... -0.16794918  0.97332281
  -0.07256132]
 ...
 [-0.67672457 -0.04282429  1.53293424 ... -0.01590621  0.09333268
   0.20331871]
 [-0.73351789  0.47511127  0.51019444 ...  0.62206509 -0.28344874
  -0.45503394]
 [ 0.08166202  0.22038886  0.01092798 ... -0.13444951  1.11055117
  -0.13720853]]


**PRINCIPAL COMPONENT ANALYSIS (PCA)**

In [69]:
pca = PCA(n_components = 2)
X1_train = pca.fit_transform(X1_train)
X1_test = pca.transform(X1_test)

In [70]:
pca.explained_variance_ratio_.sum()

1.0

In [71]:
print(pca.explained_variance_ratio_)

[0.74002383 0.25997617]


In [72]:
print(pca.singular_values_)

[74.10086144 43.92048957]


In [77]:
#pcadataset = pd.DataFrame(data = pca, columns = ['principal component 1', 'principal component 2'])